version: '3.2'
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: api
      MYSQL_PASSWORD: api
      MYSQL_DATABASE: kpt
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - type: bind
        source: ./docker/db/data
        target: /var/lib/mysql
      - type: bind
        source: ./docker/db/my.cnf
        target: /etc/mysql/conf.d/my.cnf
      - type: bind
        source: ./docker/db/init
        target: /docker-entrypoint-initdb.d
    networks:
      - default
  api:
    image: myapi:latest
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - default
  slack:
    image: myslack:latest
    build:
      context: ./
      dockerfile: ./docker/slack/Dockerfile
    depends_on:
      - api
    networks:
      - default
    secrets:
      - slack_token
secrets:
  slack_token:
    file: ./docker/slack/token.txt
