version: '3.2'
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: api
      MYSQL_PASSWORD: api
      MYSQL_DATABASE: kpt
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - type: bind
        source: ./db/data
        target: /var/lib/mysql
      - type: bind
        source: ./db/my.cnf
        target: /etc/mysql/conf.d/my.cnf
      - type: bind
        source: ./db/init
        target: /docker-entrypoint-initdb.d